language: python
python:
    - "2.7"
# command to install dependencies
install:
      - "pip install -r requirements.txt"
# command to run tests
script:
        - "python --version"
        - "pylint --version"
        - "PYTHONPATH=./snapwatchd:./drivers pylint --rcfile=tests/pylintrc ./drivers/*.py"
        - "cd drivers; nosetests --with-coverage -c ../.noserc ../tests/test_*.py"
after_success:
        coveralls
branches:
    except:
        - xs64bit
