language: python
python:
    - "2.6"
    - "2.7"
# command to install dependencies
before_install:
     - "sudo add-apt-repository ppa:fkrull/deadsnakes -y"
     - "sudo apt-get update -qq"
     - "sudo apt-get install -qq python2.4 python2.4-dev"
install:
     - "pip install -r requirements.txt --use-mirrors"
# command to run tests
script:
     - "python --version"
     - "cd drivers; nosetests --with-coverage -c ../.noserc ../tests/test_*.py"
     - "which python2.4"
     - "which nosetests"
     - "cd drivers; python2.4 /usr/bin/nosetests --with-coverage -c ../.noserc ../tests/test_*.py"
after_success:
     coveralls
