language: python
python:
    - "2.6"
    - "2.7"
# command to install dependencies
install:
     - "pip install -r requirements.txt --use-mirrors"
# command to run tests
script:
     - "cd drivers; nosetests --with-coverage -c ../.noserc ../tests/test_*.py"
after_success:
     coveralls
